In [1]:
import pandas as pd

In [6]:
# load file
file_path = r"C:\Users\Admin\Desktop\Workspace\Neo4j Project\Mall Analytics Project\Data set\Raw Data\mall_raw_data_2024_2026.csv"

df= pd.read_csv(file_path)
print("print data load")

print data load

In [7]:
print(df.shape)

(2000, 13)

In [8]:
df.head()

,Date,Customer_ID,Shop_ID,Shop_Name,Category,Product_Name,Quantity,Unit_Price,Discount,Sales_Amount,Payment_Method,Customer_Type,Rating
0,2024-01-01,C0456,S007,Sports Arena,Sports,Football,2,899,10,1618.20,Cash,Member,4
1,2024-01-01,C0266,S002,Style Point,Fashion,T-Shirt,3,799,0,2397.00,Cash,Non-Member,5
2,2024-01-05,C0077,S002,Style Point,Fashion,Jacket,1,2499,5,2374.05,UPI,Member,5
3,2024-01-07,C0133,S007,Sports Arena,Sports,Yoga Mat,3,799,10,2157.30,Cash,Member,4
4,2024-01-07,C0049,S002,Style Point,Fashion,Jeans,1,1499,5,1424.05,Card,Member,5

In [11]:
df.columns

Index(['Date', 'Customer_ID', 'Shop_ID', 'Shop_Name', 'Category',
       'Product_Name', 'Quantity', 'Unit_Price', 'Discount', 'Sales_Amount',
       'Payment_Method', 'Customer_Type', 'Rating'],
      dtype='object')

In [13]:
df["Date"] = pd.to_datetime(df["Date"])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2000 non-null   datetime64[ns]
 1   Customer_ID     2000 non-null   object
 2   Shop_ID         2000 non-null   object
 3   Shop_Name       2000 non-null   object
 4   Category        2000 non-null   object
 5   Product_Name    2000 non-null   object
 6   Quantity        2000 non-null   int64
 7   Unit_Price      2000 non-null   int64
 8   Discount        2000 non-null   int64
 9   Sales_Amount    2000 non-null   float64
 10  Payment_Method  2000 non-null   object
 11  Customer_Type   2000 non-null   object
 12  Rating          2000 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(4), object(7)
memory usage: 203.3+ KB

In [15]:
missing = df.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df[df.duplicated()]

Empty DataFrame
Columns: [Date, Customer_ID, Shop_ID, Shop_Name, Category, Product_Name, Quantity, Unit_Price, Discount, Sales_Amount, Payment_Method, Customer_Type, Rating]
Index: []

In [18]:
df["Quantity"].min(), df["Quantity"].max()

(np.int64(1), np.int64(3))

In [19]:
clean_file_path = r"C:\Users\Admin\Desktop\Workspace\Neo4j Project\Mall Analytics Project\Data set\mall_cleaned_data_2024_2026.csv"

df.to_csv(clean_file_path, index=False)

print("Cleaned dataset saved")
print("Shape:", df.shape)

Cleaned dataset saved
Shape: (2000, 13)

In [21]:
# Extract unique customers
customers = df[["Customer_ID", "Customer_Type"]].drop_duplicates()

customers_path = r"C:\Users\Admin\Desktop\Workspace\Neo4j Project\Mall Analytics Project\Data set\customers.csv"
customers.to_csv(customers_path, index=False)

print("customers.csv created!")
print("Rows:", len(customers))

customers.csv created!
Rows: 862

In [22]:
# Extract unique shops
shops = df[["Shop_ID", "Shop_Name", "Category"]].drop_duplicates()

shops_path = r"C:\Users\Admin\Desktop\Workspace\Neo4j Project\Mall Analytics Project\Data set\shops.csv"
shops.to_csv(shops_path, index=False)

print("shops.csv created!")
print("Rows:", len(shops))

shops.csv created!
Rows: 8

In [23]:
transactions = df[
    [
        "Date",
        "Customer_ID",
        "Shop_ID",
        "Product_Name",
        "Quantity",
        "Unit_Price",
        "Discount",
        "Sales_Amount",
        "Payment_Method",
        "Rating"
    ]
].copy()

transactions_path = r"C:\Users\Admin\Desktop\Workspace\Neo4j Project\Mall Analytics Project\Data set\transactions.csv"
transactions.to_csv(transactions_path, index=False)

print("transactions.csv created!")
print("Rows:", len(transactions))

transactions.csv created!
Rows: 2000

In [24]:
print("Customers:", customers.shape)
print("Shops:", shops.shape)
print("Transactions:", transactions.shape)

Customers: (862, 2)
Shops: (8, 3)
Transactions: (2000, 10)